package controllers

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"
	"testing"
	"time"

	"github.com/google/uuid"
	"gorm.io/driver/postgres"
	"gorm.io/gorm"
)

type postSearchExplainPlan struct {
	Plan postSearchExplainNode `json:"Plan"`
}

type postSearchExplainNode struct {
	IndexName string                  `json:"Index Name"`
	Plans     []postSearchExplainNode `json:"Plans"`
}

func TestPostSearchQueryPlanIntegration(t *testing.T) {
	dsn := strings.TrimSpace(os.Getenv("POSTGRES_TEST_DSN"))
	if dsn == "" {
		t.Skip("POSTGRES_TEST_DSN is not set")
	}
	db, err := gorm.Open(postgres.Open(dsn), &gorm.Config{})
	if err != nil {
		t.Fatal(err)
	}
	tx := db.Begin()
	if tx.Error != nil {
		t.Fatal(tx.Error)
	}
	defer tx.Rollback()
	schema := "post_search_plan_" + strings.ReplaceAll(uuid.NewString(), "-", "")
	if err := tx.Exec("CREATE SCHEMA " + schema).Error; err != nil {
		t.Fatal(err)
	}
	if err := tx.Exec("SET LOCAL search_path TO " + schema + ", public").Error; err != nil {
		t.Fatal(err)
	}
	for _, statement := range []string{
		"CREATE EXTENSION IF NOT EXISTS pg_trgm",
		"CREATE TABLE users (id BIGINT PRIMARY KEY, deleted_at TIMESTAMPTZ NULL)",
		"CREATE TABLE posts (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, created_at TIMESTAMPTZ NOT NULL, author_id BIGINT NOT NULL, content TEXT NOT NULL, visibility TEXT NOT NULL, deleted_at TIMESTAMPTZ NULL)",
		"CREATE INDEX idx_posts_search_content_trgm ON posts USING GIN (content gin_trgm_ops) WHERE deleted_at IS NULL AND visibility = 'public'",
		"CREATE INDEX idx_posts_search_public_created ON posts (created_at DESC, id DESC) WHERE deleted_at IS NULL AND visibility = 'public'",
	} {
		if err := tx.Exec(statement).Error; err != nil {
			t.Fatal(err)
		}
	}
	if err := tx.Exec("INSERT INTO users (id) VALUES (1)").Error; err != nil {
		t.Fatal(err)
	}
	searchToken := "planrare" + strings.ReplaceAll(uuid.NewString(), "-", "")
	if err := tx.Exec(`
INSERT INTO posts (created_at, author_id, content, visibility)
SELECT NOW() - make_interval(secs => generated), 1,
       CASE WHEN generated <= 8 THEN ? || '-' || generated::text ELSE 'ordinary fixture-' || generated::text END,
       'public'
FROM generate_series(1, 20000) AS generated`, searchToken).Error; err != nil {
		t.Fatal(err)
	}
	if err := tx.Exec("ANALYZE posts").Error; err != nil {
		t.Fatal(err)
	}
	var planJSON []byte
	query := `EXPLAIN (FORMAT JSON)
SELECT posts.id, posts.created_at
FROM posts
WHERE ` + publicPostEligibilitySQL("posts") + `
  AND posts.content ILIKE ? ESCAPE '\'
  AND posts.created_at <= ?
ORDER BY posts.created_at DESC, posts.id DESC
LIMIT 21`
	if err := tx.Raw(query, "%"+searchToken+"%", time.Now().UTC()).Row().Scan(&planJSON); err != nil {
		t.Fatal(err)
	}
	var plan []postSearchExplainPlan
	if err := json.Unmarshal(planJSON, &plan); err != nil {
		t.Fatalf("decode EXPLAIN JSON: %v output=%s", err, planJSON)
	}
	if len(plan) != 1 || !postSearchPlanUsesIndex(plan[0].Plan, "idx_posts_search_content_trgm") {
		t.Fatalf("selective search plan did not use trigram index: %s", fmt.Sprint(string(planJSON)))
	}
}

func postSearchPlanUsesIndex(node postSearchExplainNode, indexName string) bool {
	if node.IndexName == indexName {
		return true
	}
	for _, child := range node.Plans {
		if postSearchPlanUsesIndex(child, indexName) {
			return true
		}
	}
	return false
}
