package controllers

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"
	"testing"
	"time"

	"Go.exchange/config"

	"github.com/google/uuid"
	"gorm.io/driver/postgres"
	"gorm.io/gorm"
)

func TestTopicBucketQueryPlanUsesMirrorMembershipIndexIntegration(t *testing.T) {
	dsn := strings.TrimSpace(os.Getenv("POSTGRES_TEST_DSN"))
	if dsn == "" {
		t.Skip("POSTGRES_TEST_DSN is not set")
	}
	db, err := gorm.Open(postgres.Open(dsn), &gorm.Config{})
	if err != nil {
		t.Fatal(err)
	}
	tx := db.Begin()
	if tx.Error != nil {
		t.Fatal(tx.Error)
	}
	defer tx.Rollback()
	schema := "topic_plan_" + strings.ReplaceAll(uuid.NewString(), "-", "")
	if err := tx.Exec("CREATE SCHEMA " + schema).Error; err != nil {
		t.Fatal(err)
	}
	if err := tx.Exec("SET LOCAL search_path TO " + schema + ", public").Error; err != nil {
		t.Fatal(err)
	}
	for _, statement := range []string{
		"CREATE TABLE users (id BIGINT PRIMARY KEY, deleted_at TIMESTAMPTZ NULL)",
		"CREATE TABLE posts (id BIGINT PRIMARY KEY, author_id BIGINT NOT NULL, created_at TIMESTAMPTZ NOT NULL, visibility TEXT NOT NULL, deleted_at TIMESTAMPTZ NULL)",
		"CREATE TABLE devdata_mirror_accounts (id BIGINT PRIMARY KEY, registry_key TEXT NOT NULL, enabled BOOLEAN NOT NULL)",
		"CREATE TABLE devdata_mirror_posts (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, mirror_account_id BIGINT NOT NULL, local_post_id BIGINT NOT NULL, source_created_at TIMESTAMPTZ NOT NULL, imported_at TIMESTAMPTZ NOT NULL, state TEXT NOT NULL)",
		"CREATE INDEX idx_devdata_mirror_posts_account_state ON devdata_mirror_posts (mirror_account_id, state, source_created_at DESC, id DESC)",
	} {
		if err := tx.Exec(statement).Error; err != nil {
			t.Fatal(err)
		}
	}
	if err := tx.Exec("INSERT INTO users (id) VALUES (1)").Error; err != nil {
		t.Fatal(err)
	}
	if err := tx.Exec(`
INSERT INTO devdata_mirror_accounts (id, registry_key, enabled)
SELECT generated, 'topic-plan-' || generated::text, generated <> 8
FROM generate_series(1, 8) AS generated`).Error; err != nil {
		t.Fatal(err)
	}
	if err := tx.Exec(`
INSERT INTO posts (id, author_id, created_at, visibility)
SELECT generated, 1, NOW() - make_interval(secs => generated % 7776000),
       CASE WHEN generated % 9 = 0 THEN 'private' ELSE 'public' END
FROM generate_series(1, 50000) AS generated`).Error; err != nil {
		t.Fatal(err)
	}
	if err := tx.Exec(`
INSERT INTO devdata_mirror_posts (mirror_account_id, local_post_id, source_created_at, imported_at, state)
SELECT ((generated - 1) % 8) + 1, generated,
       NOW() - make_interval(secs => generated % 7776000), NOW() - INTERVAL '1 second',
       CASE WHEN generated % 11 = 0 THEN 'tombstone' ELSE 'active' END
FROM generate_series(1, 50000) AS generated`).Error; err != nil {
		t.Fatal(err)
	}
	if err := tx.Exec("ANALYZE devdata_mirror_posts").Error; err != nil {
		t.Fatal(err)
	}
	if err := tx.Exec("ANALYZE devdata_mirror_accounts").Error; err != nil {
		t.Fatal(err)
	}
	if err := tx.Exec("ANALYZE posts").Error; err != nil {
		t.Fatal(err)
	}

	topic := config.CuratedTopic{Slug: "plan", SourceKeys: []string{"topic-plan-1", "topic-plan-2"}}
	anchor := time.Now().UTC()
	query, args, err := topicBucketCandidatesQuery(topic, anchor, 7654321, 0, nil, 21)
	if err != nil {
		t.Fatal(err)
	}
	var planJSON []byte
	if err := tx.Raw("EXPLAIN (FORMAT JSON)\n"+query, args...).Row().Scan(&planJSON); err != nil {
		t.Fatal(err)
	}
	var plan []postSearchExplainPlan
	if err := json.Unmarshal(planJSON, &plan); err != nil {
		t.Fatalf("decode EXPLAIN JSON: %v output=%s", err, planJSON)
	}
	if len(plan) != 1 || !postSearchPlanUsesIndex(plan[0].Plan, "idx_devdata_mirror_posts_account_state") {
		t.Fatalf("current-bucket query plan did not use the mirror membership/source-time index: %s", fmt.Sprint(string(planJSON)))
	}
}
