version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # =======================================================
    # =======================================================
    volumes:
      - .:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
    
    command: sleep infinity
    ports:
      - "3000:3000"
    
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0
    container_name: some-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "test"
    volumes:
      - mysql-data:/var/lib/mysql
      
    ports:
      - "3306:3306"

  redis:
    image: "redis:alpine"
    container_name: some-redis
    ports:
      - "6379:6379"
      - "6060:6060"
    volumes:
      - redis-data:/data
      
  # Kafka (KRaft模式) 
  kafka:
    image: bitnamilegacy/kafka:latest
    container_name: kafka
    ports:
      - "9094:9094" # 给宿主机用的端口
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # 定义两个监听器：INTERNAL用于容器间通信，EXTERNAL用于宿主机访问
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    volumes:
      - kafka_data:/bitnami/kafka

  # === 新增：Kafka UI (可视化界面) ===
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      # UI 连接 Kafka 使用内部端口 9092
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

volumes:
  mysql-data:
  redis-data:
  kafka_data: